### ISSUE TITLE
Create structure files

### ISSUE THREAD

**Issue by safamohanna95** [GSG-FC03/ToDoList-team6#2]
**Tasks:**
- [x] create index.html
- [x] create css folder
- [x] create JS floder  
- [x] connect HTML with css and JS
